export const DECORATIONS_MAP = {
  box: { col: 0, row: 0, width: 1, height: 1 },
  boxes: { col: 1, row: 0, width: 1, height: 1 },
  barrel: { col: 2, row: 0, width: 1, height: 1 },
  barrels: { col: 3, row: 0, width: 1, height: 1 },
  stool: { col: 4, row: 0, width: 1, height: 1 },
  cauldron: { col: 5, row: 0, width: 1, height: 1 },
  stump_cleaver: { col: 6, row: 0, width: 1, height: 1 },
  stump_axe: { col: 7, row: 0, width: 1, height: 1 },
  small_table: { col: 8, row: 0, width: 1, height: 1 },
  chair: { col: 9, row: 0, width: 1, height: 1 },
  apples_small: { col: 10, row: 0, width: 1, height: 1 },
  apples_large: { col: 11, row: 0, width: 1, height: 1 },
  bottles_large: { col: 12, row: 0, width: 1, height: 1 },
  ////
  tent_1: { col: 0, row: 1, width: 3, height: 2 },
  tent_2: { col: 3, row: 1, width: 3, height: 2 },
  log_pile: { col: 6, row: 2, width: 2, height: 1 },
  table_with_food: { col: 8, row: 1, height: 1, width: 2 },
  table: { col: 8, row: 2, height: 1, width: 2 },
  apple: { col: 10, row: 2, width: 1, height: 1 },
  basket_of_apples: { col: 11, row: 2, width: 1, height: 1 },
  bottles_small: { col: 12, row: 2, width: 1, height: 1 },
  basket: { col: 10, row: 3, width: 1, height: 1 },
  bread_basket: { col: 11, row: 3, width: 1, height: 1 },
  bottle: { col: 12, row: 3, width: 1, height: 1 },
  ////
  unlit_fire: { row: 3, col: 0, width: 1, height: 1 },
  unlite_fire_cauldron: { row: 3, col: 1, width: 1, height: 1 },
  clothing_washer: { row: 3, col: 2, width: 1, height: 1 },
  bucket_1: { row: 3, col: 3, width: 1, height: 1 },
  bucket_2: { row: 3, col: 4, width: 1, height: 1 },
  towel: { row: 3, col: 5, width: 1, height: 1 },
  tombstone_1: { row: 3, col: 6, width: 1, height: 1 },
  tombstone_2: { row: 3, col: 7, width: 1, height: 1 },
  tombstone_3: { row: 3, col: 8, width: 1, height: 1 },
  tombstone_4: { row: 3, col: 9, width: 1, height: 1 },
  tombstone_5: { row: 3, col: 10, width: 1, height: 1 },
  small_pumpkin: { row: 3, col: 11, width: 1, height: 1 },
  large_pumpkin: { row: 3, col: 12, width: 1, height: 1 },
  /////
  normal_grass_rocks: { col: 0, row: 4, width: 1, height: 1 },
  normal_grass: { col: 1, row: 4, width: 1, height: 1 },
  normal_grass_small: { col: 2, row: 4, width: 1, height: 1 },
  swamp_grass_small: { col: 9, row: 5, width: 1, height: 1 },
  swamp_grass_large: { col: 10, row: 4, width: 1, height: 2 },
  fall_grass_rocks: { col: 3, row: 4, width: 1, height: 1 },
  fall_grass: { col: 4, row: 4, width: 1, height: 1 },
  fall_grass_small: { col: 5, row: 4, width: 1, height: 1 },
  winter_grass_rocks: { col: 6, row: 4, width: 1, height: 1 },
  winter_grass: { col: 7, row: 4, width: 1, height: 1 },
  winter_grass_small: { col: 8, row: 4, width: 1, height: 1 },
  brick_wall: { row: 4, col: 11, width: 2, height: 2 },
  normal_grass_rocks_2: { row: 5, col: 0, width: 1, height: 1 },
  normal_rocks_md: { row: 5, col: 1, width: 1, height: 1 },
  normal_rocks_sm: { row: 5, col: 2, width: 1, height: 1 },
  fall_grass_rocks_2: { row: 5, col: 3, width: 1, height: 1 },
  fall_rocks_md: { row: 5, col: 4, width: 1, height: 1 },
  fall_rocks_sm: { row: 5, col: 5, width: 1, height: 1 },
  winter_grass_rocks_2: { row: 5, col: 6, width: 1, height: 1 },
  winter_rocks_md: { row: 5, col: 7, width: 1, height: 1 },
  winter_rocks_sm: { row: 5, col: 8, width: 1, height: 1 },
  normal_grass_2: { row: 6, col: 0, width: 1, height: 1 },
  normal_rock_2: { row: 6, col: 1, width: 2, height: 1 },
  fall_grass_2: { row: 6, col: 3, width: 1, height: 1 },
  fall_rock_2: { row: 6, col: 4, width: 2, height: 1 },
  winter_grass_2: { row: 6, col: 6, width: 1, height: 1 },
  winter_rock_2: { row: 6, col: 7, width: 2, height: 1 },
  normal_rock_3: { row: 7, col: 0, width: 1, height: 1 },
  normal_rock_4: { row: 7, col: 1, width: 2, height: 1 },
  fall_rock_3: { row: 7, col: 3, height: 1, width: 1 },
  fall_rock_4: { row: 7, col: 4, height: 1, width: 1 },
  winter_rock_3: { row: 7, col: 6, width: 1, height: 1 },
  winter_rock_4: { row: 7, col: 7, width: 2, height: 1 },
  scarecrow: { row: 6, col: 9, width: 2, height: 2 },
  jackolantern_1: { row: 6, col: 11, width: 1, height: 1 },
  jackolantern_2: { row: 6, col: 12, width: 1, height: 1 },
  normal_rockpile: { row: 8, col: 0, width: 3, height: 2 },
  rockpile: { row: 8, col: 3, width: 3, height: 2 },
  fall_rockpile: { row: 8, col: 6, width: 3, height: 2 },
  winter_rockpile: { row: 8, col: 9, width: 3, height: 2 },
  statue: { row: 8, col: 12, width: 1, height: 2 },
  fall_leafpile: { row: 10, col: 5, width: 3, height: 1 },
  winter_snowpile: { row: 10, col: 8, width: 3, height: 1 },
  clothes_line: { row: 11, col: 0, width: 5, height: 2 },
  fall_leafpile_sm: { row: 11, col: 5, width: 2, height: 1 },
  winter_snowpile_sm: { row: 11, col: 7, width: 2, height: 1 },
  normal_bush_lg: { row: 13, col: 0, width: 2, height: 1 },
  normal_bush_md: { row: 13, col: 2, width: 1, height: 1 },
  normal_bush_sm: { row: 13, col: 3, width: 1, height: 1 },

  fall_bush_lg: { row: 14, col: 0, width: 2, height: 1 },
  fall_bush_md: { row: 14, col: 2, width: 1, height: 1 },
  fall_bush_sm: { row: 14, col: 3, width: 1, height: 1 },

  winter_bush_lg: { row: 15, col: 0, width: 2, height: 1 },
  winter_bush_md: { row: 15, col: 2, width: 1, height: 1 },
  winter_bush_sm: { row: 16, col: 3, width: 1, height: 1 },
};

export const mountainDecorations = [
  "normal_grass_rocks",
  "normal_grass_rocks_2",
  "normal_rocks_small",
  "normal_rock_2",
  "normal_rock_3",
  "normal_rock_4",
];
